# Generated by Django 4.1.7 on 2023-02-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_score_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='owner',
            new_name='user',
        ),
    ]
